# Generated by Django 6.0.3 on 2026-03-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_filename", models.CharField(max_length=255, unique=True)),
                (
                    "result_type",
                    models.CharField(
                        choices=[("gait", "Gait"), ("symptoms", "Symptoms")],
                        max_length=32,
                    ),
                ),
                (
                    "video_filename",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
